version: '3.5'
services:
  db:
    container_name: linksdb
    image: postgres
    volumes:
      - type: volume
        source: favlinks-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    # restart: always
  web:
    container_name: webapp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./favlinks:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    depends_on:
      - db
volumes:
  favlinks-data: