runtime: python311
env: standard
instance_class: F1
# entrypoint: gunicorn -b :$PORT favlinks.wsgi
handlers:
- url: /static
  static_dir: static/
- url: .*
  script: auto
env_variables:
  IS_APP_ENGINE: 1
  # APPENGINE_URL: PROJECT_ID.uc.r.appspot.com
