# Generated by Django 5.0 on 2024-04-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblink", "0002_alter_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="weblink.url",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="last_preview_capture",
            field=models.DateTimeField(null=True, verbose_name="preview fetched"),
        ),
    ]
