# Generated by Django 5.0 on 2024-04-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblink", "0003_alter_link_title_alter_link_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="value",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
