# Generated by Django 5.0 on 2024-04-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weblink", "0005_alter_category_options_alter_link_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="url_count",
            new_name="link_count",
        ),
        migrations.RemoveField(
            model_name="url",
            name="tags",
        ),
    ]
