# Generated by Django 5.0 on 2024-04-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblink", "0006_rename_url_count_tag_link_count_remove_url_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="state",
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="link",
            name="url_hash",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
