# Generated by Django 5.0 on 2024-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblink", "0007_link_state_link_url_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="tags",
            field=models.ManyToManyField(to="weblink.tag"),
        ),
    ]
